/**
 *
 * @author Carlos I. M., Tatiana L., Carolina A., Facundo K., Gabriel Z.
 * Un gran equipo
 
 */
package Ejercicio2;

public class Espejo extends javax.swing.JFrame {

    /**
     * Creates new form EspejoUI
     */
    public Espejo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOriginal = new javax.swing.JPanel();
        etiquetaOriginal = new javax.swing.JLabel();
        comboBoxOriginal = new javax.swing.JComboBox<>();
        sliderOriginal = new javax.swing.JSlider();
        textFieldOriginal = new javax.swing.JTextField();
        spinnerOriginal = new javax.swing.JSpinner();
        opcion5 = new javax.swing.JCheckBox();
        opcion4 = new javax.swing.JCheckBox();
        opcion6 = new javax.swing.JCheckBox();
        opcion2 = new javax.swing.JRadioButton();
        opcion3 = new javax.swing.JRadioButton();
        opcion1 = new javax.swing.JRadioButton();
        separador = new javax.swing.JSeparator();
        panelEspejo = new javax.swing.JPanel();
        etiquetaEspejo = new javax.swing.JLabel();
        opcion1Espejo = new javax.swing.JRadioButton();
        opcion2Espejo = new javax.swing.JRadioButton();
        opcion3Espejo = new javax.swing.JRadioButton();
        opcion4Espejo = new javax.swing.JCheckBox();
        opcion5Espejo = new javax.swing.JCheckBox();
        opcion6Espejo = new javax.swing.JCheckBox();
        textFieldEspejo = new javax.swing.JTextField();
        spinnerEspejo = new javax.swing.JSpinner();
        comboBoxEspejo = new javax.swing.JComboBox<>();
        sliderEspejo = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaOriginal.setText("Original");

        comboBoxOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxOriginalItemStateChanged(evt);
            }
        });

        sliderOriginal.setMajorTickSpacing(1);
        sliderOriginal.setMaximum(20);
        sliderOriginal.setPaintLabels(true);
        sliderOriginal.setPaintTicks(true);
        sliderOriginal.setValue(0);
        sliderOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderOriginalStateChanged(evt);
            }
        });

        textFieldOriginal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textFieldOriginalPropertyChange(evt);
            }
        });

        spinnerOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerOriginalStateChanged(evt);
            }
        });

        opcion5.setText("Opción 5");
        opcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion5ActionPerformed(evt);
            }
        });

        opcion4.setText("Opción 4");
        opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion4ActionPerformed(evt);
            }
        });

        opcion6.setText("Opción 6");
        opcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion6ActionPerformed(evt);
            }
        });

        opcion2.setText("Opción 2");
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        opcion3.setText("Opción 3");
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        opcion1.setText("Opción 1");
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOriginalLayout = new javax.swing.GroupLayout(panelOriginal);
        panelOriginal.setLayout(panelOriginalLayout);
        panelOriginalLayout.setHorizontalGroup(
            panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador)
                    .addGroup(panelOriginalLayout.createSequentialGroup()
                        .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOriginalLayout.createSequentialGroup()
                                .addComponent(opcion2)
                                .addGap(18, 18, 18)
                                .addComponent(opcion5)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOriginalLayout.createSequentialGroup()
                                    .addComponent(opcion1)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcion4)
                                    .addGap(18, 18, 18)
                                    .addComponent(textFieldOriginal))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOriginalLayout.createSequentialGroup()
                                    .addComponent(opcion3)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcion6)
                                    .addGap(18, 18, 18)
                                    .addComponent(spinnerOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelOriginalLayout.createSequentialGroup()
                .addComponent(etiquetaOriginal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelOriginalLayout.setVerticalGroup(
            panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion1)
                    .addComponent(opcion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion2)
                    .addComponent(opcion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOriginalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sliderOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opcion3)
                        .addComponent(opcion6)
                        .addComponent(spinnerOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        etiquetaEspejo.setText("Espejo");

        opcion1Espejo.setText("Opción 1");
        opcion1Espejo.setEnabled(false);

        opcion2Espejo.setText("Opción 2");
        opcion2Espejo.setEnabled(false);

        opcion3Espejo.setText("Opción 3");
        opcion3Espejo.setEnabled(false);

        opcion4Espejo.setText("Opción 4");
        opcion4Espejo.setEnabled(false);

        opcion5Espejo.setText("Opción 5");
        opcion5Espejo.setEnabled(false);

        opcion6Espejo.setText("Opción 6");
        opcion6Espejo.setEnabled(false);

        textFieldEspejo.setEnabled(false);

        spinnerEspejo.setEnabled(false);

        comboBoxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEspejo.setEnabled(false);

        sliderEspejo.setMajorTickSpacing(1);
        sliderEspejo.setMaximum(20);
        sliderEspejo.setPaintLabels(true);
        sliderEspejo.setPaintTicks(true);
        sliderEspejo.setValue(0);
        sliderEspejo.setEnabled(false);

        javax.swing.GroupLayout panelEspejoLayout = new javax.swing.GroupLayout(panelEspejo);
        panelEspejo.setLayout(panelEspejoLayout);
        panelEspejoLayout.setHorizontalGroup(
            panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspejoLayout.createSequentialGroup()
                .addComponent(etiquetaEspejo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelEspejoLayout.createSequentialGroup()
                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEspejoLayout.createSequentialGroup()
                        .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcion1Espejo)
                            .addComponent(opcion2Espejo)
                            .addComponent(opcion3Espejo))
                        .addGap(18, 18, 18)
                        .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEspejoLayout.createSequentialGroup()
                                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcion4Espejo)
                                    .addComponent(opcion5Espejo))
                                .addGap(18, 18, 18)
                                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelEspejoLayout.createSequentialGroup()
                                .addComponent(opcion6Espejo)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelEspejoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sliderEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEspejoLayout.setVerticalGroup(
            panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspejoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaEspejo)
                .addGap(17, 17, 17)
                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion1Espejo)
                    .addComponent(opcion4Espejo)
                    .addComponent(textFieldEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion2Espejo)
                    .addComponent(opcion5Espejo)
                    .addComponent(comboBoxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspejoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion3Espejo)
                    .addComponent(opcion6Espejo)
                    .addComponent(spinnerEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(sliderEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelEspejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEspejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1ActionPerformed
        if (opcion1.isSelected()) {
            opcion1Espejo.setSelected(true);
        } else {
            opcion1Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion1ActionPerformed

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        if (opcion2.isSelected()) {
            opcion2Espejo.setSelected(true);
        } else {
            opcion2Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        if (opcion3.isSelected()) {
            opcion3Espejo.setSelected(true);
        } else {
            opcion3Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion3ActionPerformed

    private void opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion4ActionPerformed
        if (opcion4.isSelected()) {
            opcion4Espejo.setSelected(true);
        } else {
            opcion4Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion4ActionPerformed

    private void opcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion5ActionPerformed
        if (opcion5.isSelected()) {
            opcion5Espejo.setSelected(true);
        } else {
            opcion5Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion5ActionPerformed

    private void opcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion6ActionPerformed
        if (opcion6.isSelected()) {
            opcion6Espejo.setSelected(true);
        } else {
            opcion6Espejo.setSelected(false);
        }
    }//GEN-LAST:event_opcion6ActionPerformed

    private void sliderOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderOriginalStateChanged
        sliderEspejo.setValue(sliderOriginal.getValue());
    }//GEN-LAST:event_sliderOriginalStateChanged

    private void comboBoxOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxOriginalItemStateChanged
        comboBoxEspejo.setSelectedItem(comboBoxOriginal.getSelectedItem());
    }//GEN-LAST:event_comboBoxOriginalItemStateChanged

    private void spinnerOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerOriginalStateChanged
        spinnerEspejo.setValue(spinnerOriginal.getValue());
    }//GEN-LAST:event_spinnerOriginalStateChanged

    private void textFieldOriginalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textFieldOriginalPropertyChange
        textFieldEspejo.setDocument(textFieldOriginal.getDocument());
    }//GEN-LAST:event_textFieldOriginalPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxEspejo;
    private javax.swing.JComboBox<String> comboBoxOriginal;
    private javax.swing.JLabel etiquetaEspejo;
    private javax.swing.JLabel etiquetaOriginal;
    private javax.swing.JRadioButton opcion1;
    private javax.swing.JRadioButton opcion1Espejo;
    private javax.swing.JRadioButton opcion2;
    private javax.swing.JRadioButton opcion2Espejo;
    private javax.swing.JRadioButton opcion3;
    private javax.swing.JRadioButton opcion3Espejo;
    private javax.swing.JCheckBox opcion4;
    private javax.swing.JCheckBox opcion4Espejo;
    private javax.swing.JCheckBox opcion5;
    private javax.swing.JCheckBox opcion5Espejo;
    private javax.swing.JCheckBox opcion6;
    private javax.swing.JCheckBox opcion6Espejo;
    private javax.swing.JPanel panelEspejo;
    private javax.swing.JPanel panelOriginal;
    private javax.swing.JSeparator separador;
    private javax.swing.JSlider sliderEspejo;
    private javax.swing.JSlider sliderOriginal;
    private javax.swing.JSpinner spinnerEspejo;
    private javax.swing.JSpinner spinnerOriginal;
    private javax.swing.JTextField textFieldEspejo;
    private javax.swing.JTextField textFieldOriginal;
    // End of variables declaration//GEN-END:variables
}

